### ISSUE TITLE
Got an error autoget.sh: aclocal: not found

### ISSUE THREAD

**Issue by TryDevBetter** [Bifrozt/honeyd-ansible#1]
OS: Debian 9
Error: autoget.sh: aclocal: not found

**Comment by Bifrozt** [comment]
Hi, sorry about taking so long to get back to you.
Can you please provide some more info?

**Comment by Bifrozt** [comment]
Im closing this as I never received any answer to this, please let me know if you run into this again and ill see how to help out.
